@startuml
@startmindmap
'https://plantuml.com/mindmap-diagram

+ Безопасность данных
++ Конфиденциальные данные
+++ ФИО, контактные данные
++++ Утечка данных
*****[#FFBBCC]:
* Утечка персональных данных приведёт к штрафам и потере доверия клиентов
* Риск мошенничества и спама
;
++++++ Критический
++++ Подделка персональных данных
*****[#FFBBCC]:
* Потеря доступа к лк закроет возможность взаимодействия с компанией
* Мошеннические операции от другого лица
;
++++++ Критический
++++ Потеря данных
*****[#FFBBCC]:
* Сложности при работе с клиентами и их уведомлении
* Слив данных грозит использованием данных мошенниками. Прикрываясь лицом компании
мошенники смогут выкрасть дополнительную информацию у клиентов или выкрасть денежные средства
* Сложности в идентификации клиента
;
++++++ Критический
+++ ЖКУ
++++ Утечка данных
*****[#lightblue]:
* Штрафы, потеря доверия клиентов, партнеров
* Злоумышленник от лица компании сможет поддельные квитанции
;
++++++ Критический
++++ Искажение данных
*****[#lightblue]:
* Квитанции с поддельными суммами приведут к жалобам, финансовым потерям
* Ошибки в расчетах с поставщиками услуг приведут к репутационным рискам
;
++++++ Критический
++++ Потеря данных
*****[#lightblue]:
* Потеря данных приведет к невозможности поднять историю платежей клиентами в случае спорных ситуаций или партнерами
* Риск штрафов, судебных разбирательств
* Уменьшение доверия клиентов. Недоверие к ЭДО и хранение квитанций об оплате в печатном виде
;
++++++ Значительный
+++ Бронирование недвижимости
++++ Утечка данных
*****[#lightgreen]:
Утечка персональных данных приведёт к штрафам и потере доверия клиентов
;
++++++ Критический
++++ Искажение данных
*****[#lightgreen]:
* Введение в заблуждение клиентов при бронировании жилья (повторное бронирование жилья по которому уже совершена сделка)
* Потеря доверия клиентов
;
++++++ Значительный
++++ Потеря данных
*****[#lightgreen]:
* Финансовые потери компании
* Жалобы клиентов
* Проблемы с подтверждением оплаты забронированного жилья или
оплаты несколькими клиентами по одному и тому же объекту недвижимости
;
++++++ Значительный
++ Секретные данные
+++ Данные о продажах
++++ Утечка данных
*****[#lightblue]:
Утечка персональных данных приведёт к штрафам и потере доверия клиентов
;
++++++ Критический
++++ Искажение данных
*****[#lightblue]:
Недостоверные данные в финансовых отчетах повлекут к претензиям от
налоговых органов, сложности при проведении аудита, штрафам
;
++++++ Критический
++++ Потеря данных
*****[#lightblue]:
* Штрафы со стороны контролирующих органов
* При частичной или полной потере данных по сделкам теряется возможность подтвердить покупку
* Судебные разбирательства
* Финансовые потери
* Теряется возможность планирования по развитию бизнеса
;
++++++ Критический
+++ Данные с платежных карт
++++ Утечка данных
*****[#lavender]:
Утечка персональных данных приведёт к штрафам и потере доверия клиентов
;
++++++ Критический
++++ Искажение данных
*****[#lavender]:
Возможны мошеннические операции
;
++++++ Критический
++++ Потеря данных
*****[#lavender]:
Снижение доверия клиентов в надежности сервисов
;
++++++ Значительный

left side
-- Публичные данные
***:
* Открытые предложения
* Пользовательские соглашения (оферта)
;
---- Искажение данных
*****[#lightblue]:
Может ввести в заблуждение клиентов. Отсюда жалобы и судебные иски,
если публичные соглашения не будут выполнены перед клиентом
;
------ Значительный

-- Внутренние данные
***:
* Журналы логирования IT-систем
* Данные о конфигурациях оборудования
* Информация о сетевой инфраструктуре
;
---- Утечка данных
*****[#lightyellow]:
Утечка системных данных облегчит кибератаки
;
------ Критический
---- Потеря данных
*****[#lightyellow]:
* Потеря логов усложнит расследование инцидентов и диагностики сбоев.
* Несанкционированный доступ к логам может скрыть следы инцидентов безопасности
;
------ Значительный
---- Искажение данных
*****[#lightyellow]:
Хакер может скрыть следы своего присутствия (удалить логи)
;
------ Критический
***:
* Описание объектов недвижимости
* Фотографии
* Цены
* Доступность объектов для продажи
;
---- Потеря данных
*****[#orange]:
Финансовые убытки. Клиент не сможет просмотреть интересующие предложения
и может уйти к конкурентам
;
------ Значительный
---- Искажение данных
*****[#orange]:
* Совершение сделки по искаженным данным может привести к финансовым и юридическим проблемам
* Потеря доверия со стороны клиента
;
------ Значительный

@endmindmap
@enduml